<#
.SYNOPSIS
    Snapshot all mod files currently deployed in the RE4R game folder
    into a timestamped backup folder under deployment_backups\.

.DESCRIPTION
    Reads the deployed DualSenseEnhanced.lua to detect whether the
    deployed version is "dev" or "release" (RELEASE_BUILD flag), and
    names the backup accordingly:

        deployment_backups\YYYYMMDD-HHmmss-dev\
        deployment_backups\YYYYMMDD-HHmmss-release\

    WAV files under sounds\ are intentionally excluded -- they are
    Capcom assets that can be regenerated by setup_sounds.bat and can
    be hundreds of MB. Everything else (Lua, DLL, EXE, config, extractor
    tools, top-level txt/bat files) is included.

    Run this before deploying a new version to the game folder so you
    always have a known-good fallback.

.PARAMETER GamePath
    Root of the RE4R install. Defaults to the Steam path on this machine.

.PARAMETER BackupRoot
    Parent folder for backup snapshots. Defaults to deployment_backups\
    in the dev checkout root (already in .gitignore).

.EXAMPLE
    .\tools\backup_game_mod.ps1
    .\tools\backup_game_mod.ps1 -GamePath "<game-directory>"
#>
param(
    [string]$GamePath   = "C:\Program Files (x86)\Steam\steamapps\common\RESIDENT EVIL 4  BIOHAZARD RE4",
    [string]$BackupRoot = ""
)

$ErrorActionPreference = "Stop"
$repoRoot = Resolve-Path (Join-Path $PSScriptRoot "..")
if (-not $BackupRoot) { $BackupRoot = Join-Path $repoRoot "deployment_backups" }

if (-not (Test-Path $GamePath)) {
    Write-Error "Game folder not found: $GamePath"
}

# Detect dev vs release from the deployed loader.
$loaderPath = Join-Path $GamePath "reframework\autorun\DualSenseEnhanced.lua"
$buildLabel = "dev"
if (Test-Path $loaderPath) {
    $loaderText = [System.IO.File]::ReadAllText($loaderPath, [System.Text.Encoding]::UTF8)
    if ($loaderText -match "local RELEASE_BUILD = true") { $buildLabel = "release" }
}

$timestamp  = Get-Date -Format "yyyyMMdd-HHmmss"
$backupPath = Join-Path $BackupRoot "$timestamp-$buildLabel"
New-Item -ItemType Directory -Force -Path $backupPath | Out-Null

Write-Host "Game folder : $GamePath"
Write-Host "Build       : $buildLabel"
Write-Host "Backup to   : $backupPath"
Write-Host ""

# Files and subtrees owned by this mod.
# Each entry is [gameFolderRelPath, isDirectory, skipWav]
$targets = @(
    # Top-level package files at game root
    @{ rel = "reframework\autorun\DualSenseEnhanced.lua"; dir = $false }
    @{ rel = "reframework\autorun\DualSenseEnhanced";     dir = $true  }
    @{ rel = "reframework\data\RE4R_WeaponData.lua";      dir = $false }
    @{ rel = "reframework\data\DualSenseEnhanced";        dir = $true  }
    @{ rel = "reframework\plugins\DualsenseAudioBridgeLauncher.dll"; dir = $false }
    @{ rel = "DualSenseEnhanced";                         dir = $true  }
    @{ rel = "setup_sounds.bat";                          dir = $false }
    @{ rel = "README.txt";                                dir = $false }
    @{ rel = "VERSION.txt";                               dir = $false }
    @{ rel = "THIRD_PARTY_LICENSES.txt";                  dir = $false }
    @{ rel = "modinfo.ini";                               dir = $false }
)

$copied  = 0
$skipped = 0

foreach ($t in $targets) {
    $src = Join-Path $GamePath $t.rel
    if (-not (Test-Path $src)) { continue }

    if ($t.dir) {
        Get-ChildItem -Path $src -Recurse -File | ForEach-Object {
            # Skip extracted Capcom audio
            if ($_.Extension -eq ".wav") { $script:skipped++; return }

            $rel = $_.FullName.Substring($GamePath.Length).TrimStart('\')
            $dst = Join-Path $backupPath $rel
            New-Item -ItemType Directory -Force -Path (Split-Path $dst -Parent) | Out-Null
            Copy-Item $_.FullName $dst -Force
            $script:copied++
        }
    } else {
        $rel = $t.rel
        $dst = Join-Path $backupPath $rel
        New-Item -ItemType Directory -Force -Path (Split-Path $dst -Parent) | Out-Null
        Copy-Item $src $dst -Force
        $copied++
    }
}

Write-Host "Backed up $copied file(s), skipped $skipped *.wav (Capcom assets)."
Write-Host ""
Write-Host "Backup: $backupPath" -ForegroundColor Green
